-- Raw SMART/NVMe snapshot history.
-- This table is the initial SQLite schema for local agent-side history.
create table disk_snapshot
(
    -- Snapshot identity generated by the application.
    snapshot_id                      BINARY(16)   not null
        primary key,

    -- Node identity is stored with every row so the same schema can support
    -- standalone history now and hub/node-agent aggregation later.
    node_id                          BINARY(16)   not null,
    node_name                        VARCHAR(255) not null,

    -- Collection time is stored as TEXT in SQLite to preserve the serialized
    -- timestamp value without relying on a native timestamp type.
    collect_time                     TEXT         not null,

    -- device_key is the stable opaque history identity. device_path is only
    -- diagnostic/display data and may change across boots.
    device_key                       VARCHAR(255) not null,
    device_serial_name               VARCHAR(255),
    connection_protocol              VARCHAR(255) not null,
    device_model                     VARCHAR(255),
    device_path                      VARCHAR(255) not null,
    temperature_celsius              DECIMAL(5, 2),
    power_on_hours                   BIGINT,
    power_on_cycles                  BIGINT,

    -- ATA-specific counters. These stay nullable because NVMe snapshots do not
    -- have ATA SMART attributes.
    ata_reallocated_sector_count     INT,
    ata_current_pending_sector_count INT,
    ata_offline_uncorrectable_count  INT,
    ata_udma_crc_error_count         INT,

    -- NVMe-specific counters. These stay nullable because ATA snapshots do not
    -- have NVMe SMART log fields.
    nvme_percentage_used             INT,
    nvme_available_spare             INT,
    nvme_media_error_count           BIGINT,
    nvme_data_units_written          BIGINT,
    nvme_data_units_read             BIGINT,

    -- Serialized DiskSnapshot payload used to keep API responses compatible
    -- while selected columns remain query/index targets.
    snapshot_json                    BLOB         not null,

    -- SQLite does not enforce INT width. Keep these values inside the signed
    -- 32-bit range used by the Kotlin/Exposed model.
    constraint chk_disk_snapshot_signed_integer_ata_current_pending_sector_count
        check (ata_current_pending_sector_count BETWEEN -2147483648 AND 2147483647),
    constraint chk_disk_snapshot_signed_integer_ata_offline_uncorrectable_count
        check (ata_offline_uncorrectable_count BETWEEN -2147483648 AND 2147483647),
    constraint chk_disk_snapshot_signed_integer_ata_reallocated_sector_count
        check (ata_reallocated_sector_count BETWEEN -2147483648 AND 2147483647),
    constraint chk_disk_snapshot_signed_integer_ata_udma_crc_error_count
        check (ata_udma_crc_error_count BETWEEN -2147483648 AND 2147483647),
    constraint chk_disk_snapshot_signed_integer_nvme_available_spare
        check (nvme_available_spare BETWEEN -2147483648 AND 2147483647),
    constraint chk_disk_snapshot_signed_integer_nvme_percentage_used
        check (nvme_percentage_used BETWEEN -2147483648 AND 2147483647)
);

-- Bounded history queries filter by node_id + device_key and order/range by
-- collect_time.
create index disk_snapshot_node_id_device_key_collect_time
    on disk_snapshot (node_id, device_key, collect_time);
